apiVersion: v1
kind: PersistentVolume
metadata:
  name: sidecar-config
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sidecar-config-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
