apiVersion: v1
kind: Service
metadata:
  name: security-server-sidecar-consumer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    run: security-server-sidecar-consumer
spec:
  type: LoadBalancer
  selector:
    run: security-server-sidecar-consumer
  ports:
  - port: 5500
    targetPort: 5500
    protocol: TCP
    name: messaging
  - port: 5577
    targetPort: 5577
    protocol: TCP
    name: ocsp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-server-sidecar-consumer
spec:
  selector:
    matchLabels:
      run: security-server-sidecar-consumer
  replicas: 1
  template:
    metadata:
      labels:
        run: security-server-sidecar-consumer
    spec:
      volumes:
      - name: sidecar-config-volume
        persistentVolumeClaim:
          claimName: sidecar-config-claim
      containers:
      - name: security-server-sidecar
        image: niis/xroad-security-server-sidecar:latest
        volumeMounts:
        - name: sidecar-config-volume
          mountPath: /etc/xroad/
        env:
        - name: XROAD_TOKEN_PIN
          value: "12345"
        - name: XROAD_ADMIN_USER
          value: "xrd"
        - name: XROAD_ADMIN_PASSWORD
          value: "secret"
        - name: XROAD_DB_HOST
          value: "{{XROAD_DB_HOST}}"
        - name: XROAD_DB_PORT
          value: "{{XROAD_DB_PORT}}"
        - name: XROAD_DB_PWD
          value: "{{XROAD_DB_PWD}}"
        - name: XROAD_LOG_LEVEL
          value: "{{XROAD_LOG_LEVEL}}"
       
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 4000
        - containerPort: 5500
        - containerPort: 5577
        - containerPort: 5588